#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-installer
Version  : 0.7.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/05/18/ceeb4e3ab3aa54495775775b38ae42b10a92f42ce42dfa44da684289b8c8/installer-0.7.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/05/18/ceeb4e3ab3aa54495775775b38ae42b10a92f42ce42dfa44da684289b8c8/installer-0.7.0.tar.gz
Summary  : A library for installing Python wheels.
Group    : Development/Tools
License  : MIT
Requires: pypi-installer-license = %{version}-%{release}
Requires: pypi-installer-python = %{version}-%{release}
Requires: pypi-installer-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# installer
<!-- start readme-pitch -->
This is a low-level library for installing a Python package from a
[wheel distribution](https://packaging.python.org/glossary/#term-Wheel). It
provides basic functionality and abstractions for handling wheels and installing
packages from wheels.

%package license
Summary: license components for the pypi-installer package.
Group: Default

%description license
license components for the pypi-installer package.


%package python
Summary: python components for the pypi-installer package.
Group: Default
Requires: pypi-installer-python3 = %{version}-%{release}

%description python
python components for the pypi-installer package.


%package python3
Summary: python3 components for the pypi-installer package.
Group: Default
Requires: python3-core
Provides: pypi(installer)

%description python3
python3 components for the pypi-installer package.


%prep
%setup -q -n installer-0.7.0
cd %{_builddir}/installer-0.7.0
pushd ..
cp -a installer-0.7.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1679326636
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m flit_core.wheel

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-installer
cp %{_builddir}/installer-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-installer/0b6acd5f74af73eb349bc2a896b96835436b5085 || :
cd src
python3 -m installer --destdir=%{buildroot} ../dist/*.whl

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-installer/0b6acd5f74af73eb349bc2a896b96835436b5085

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
